import 'Car.dart';

final List<Car> cars = [
  Car(
    id: "MTINNO1500", 
    name: "Toyota Innova 2.5V 2015", 
    price: 550000000, 
    transactionDate: "2015-01-01", 
    color: "Hitam", 
    mileage: "1000", 
    location: "Surabaya",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum vitae velit nec neque volutpat condimentum ut at enim. Phasellus sed porttitor elit. Duis tincidunt sem erat, non lacinia magna vehicula id.",
  ),
  Car(
    id: "MTINNO1501", 
    name: "Toyota Innova 2.5V 2015", 
    price: 500000000, 
    transactionDate: "2015-01-31", 
    color: "Hitam", 
    mileage: "1000", 
    location: "Surabaya",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum vitae velit nec neque volutpat condimentum ut at enim. Phasellus sed porttitor elit. Duis tincidunt sem erat, non lacinia magna vehicula id.",
  ),
  Car(
    id: "MTINNO1502", 
    name: "Toyota Innova 2.5V 2015", 
    price: 400000000, 
    transactionDate: "2016-11-30", 
    color: "Putih", 
    mileage: "10000", 
    location: "DKI Jakarta",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum vitae velit nec neque volutpat condimentum ut at enim. Phasellus sed porttitor elit. Duis tincidunt sem erat, non lacinia magna vehicula id.",
  ),
  Car(
    id: "MTINNO1503", 
    name: "Toyota Innova 2.5V 2015", 
    price: 335000000, 
    transactionDate: "2017-02-02", 
    color: "Silver", 
    mileage: "25000", 
    location: "DKI Jakarta",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum vitae velit nec neque volutpat condimentum ut at enim. Phasellus sed porttitor elit. Duis tincidunt sem erat, non lacinia magna vehicula id.",
  ),
  Car(
    id: "MTINNO1504", 
    name: "Toyota Innova 2.5V 2015", 
    price: 300000000, 
    transactionDate: "2017-04-20", 
    color: "Putih", 
    mileage: "26000", 
    location: "Bandung",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum vitae velit nec neque volutpat condimentum ut at enim. Phasellus sed porttitor elit. Duis tincidunt sem erat, non lacinia magna vehicula id.",
  ),
  Car(
    id: "MTINNO1505", 
    name: "Toyota Innova 2.5V 2015", 
    price: 200000000, 
    transactionDate: "2018-03-03", 
    color: "Abu-Abu", 
    mileage: "40000", 
    location: "DKI Jakarta",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum vitae velit nec neque volutpat condimentum ut at enim. Phasellus sed porttitor elit. Duis tincidunt sem erat, non lacinia magna vehicula id.",
  ),
];